# Copyright (c) 2011 The Chromium Embedded Framework Authors. All rights
# reserved. Use of this source code is governed by a BSD-style license that
# can be found in the LICENSE file.

# Explicit source lists for the myapp fork (webagent / websimple).
#
# This file is intentionally decoupled from cef_paths2.gypi: the "tests" tree
# is kept pristine so CEF can be upgraded cleanly, while "myapp" evolves
# independently. Each file below is listed literally (no path remapping), so
# renamed resources (webagent.ico / websimple.ico) and myapp-only additions
# (the hostclr CLR bridge) are handled correctly. Only Windows and Linux are
# wired up; macOS is not forked here.
#
# Read by cef/BUILD.gn via tools/gypi_to_gn.py.

{
  'variables': {
    'myapp_shared_sources_browser': [
      'myapp/shared/browser/client_app_browser.cc',
      'myapp/shared/browser/client_app_browser.h',
      'myapp/shared/browser/file_util.cc',
      'myapp/shared/browser/file_util.h',
      'myapp/shared/browser/geometry_util.cc',
      'myapp/shared/browser/geometry_util.h',
      'myapp/shared/browser/main_message_loop.cc',
      'myapp/shared/browser/main_message_loop.h',
      'myapp/shared/browser/main_message_loop_external_pump.cc',
      'myapp/shared/browser/main_message_loop_external_pump.h',
      'myapp/shared/browser/main_message_loop_std.cc',
      'myapp/shared/browser/main_message_loop_std.h',
      'myapp/shared/browser/resource_util.h',
    ],
    'myapp_shared_sources_common': [
      'myapp/shared/common/binary_value_utils.cc',
      'myapp/shared/common/binary_value_utils.h',
      'myapp/shared/common/client_app.cc',
      'myapp/shared/common/client_app.h',
      'myapp/shared/common/client_app_other.cc',
      'myapp/shared/common/client_app_other.h',
      'myapp/shared/common/client_switches.cc',
      'myapp/shared/common/client_switches.h',
      'myapp/shared/common/string_util.cc',
      'myapp/shared/common/string_util.h',
    ],
    'myapp_shared_sources_renderer': [
      'myapp/shared/renderer/client_app_renderer.cc',
      'myapp/shared/renderer/client_app_renderer.h',
    ],
    'myapp_shared_sources_resources': [
      'myapp/shared/resources/osr_test.html',
      'myapp/shared/resources/pdf.html',
      'myapp/shared/resources/pdf.pdf',
      'myapp/shared/resources/window_icon.1x.png',
      'myapp/shared/resources/window_icon.2x.png',
    ],
    'myapp_shared_sources_linux': [
      'myapp/shared/browser/main_message_loop_external_pump_linux.cc',
      'myapp/shared/browser/resource_util_posix.cc',
    ],
    'myapp_shared_sources_win': [
      'myapp/shared/browser/main_message_loop_external_pump_win.cc',
      'myapp/shared/browser/resource_util_win.cc',
      'myapp/shared/browser/util_win.cc',
      'myapp/shared/browser/util_win.h',
    ],
    'myapp_cefclient_sources_browser': [
      'myapp/cefclient/browser/base_client_handler.cc',
      'myapp/cefclient/browser/base_client_handler.h',
      'myapp/cefclient/browser/binary_transfer_test.cc',
      'myapp/cefclient/browser/binary_transfer_test.h',
      'myapp/cefclient/browser/binding_test.cc',
      'myapp/cefclient/browser/binding_test.h',
      'myapp/cefclient/browser/browser_window.cc',
      'myapp/cefclient/browser/browser_window.h',
      'myapp/cefclient/browser/bytes_write_handler.cc',
      'myapp/cefclient/browser/bytes_write_handler.h',
      'myapp/cefclient/browser/client_app_delegates_browser.cc',
      'myapp/cefclient/browser/client_browser.cc',
      'myapp/cefclient/browser/client_browser.h',
      'myapp/cefclient/browser/client_handler.cc',
      'myapp/cefclient/browser/client_handler.h',
      'myapp/cefclient/browser/client_handler_osr.cc',
      'myapp/cefclient/browser/client_handler_osr.h',
      'myapp/cefclient/browser/client_handler_std.cc',
      'myapp/cefclient/browser/client_handler_std.h',
      'myapp/cefclient/browser/client_prefs.cc',
      'myapp/cefclient/browser/client_prefs.h',
      'myapp/cefclient/browser/client_types.h',
      'myapp/cefclient/browser/component_test.cc',
      'myapp/cefclient/browser/component_test.h',
      'myapp/cefclient/browser/config_test.cc',
      'myapp/cefclient/browser/config_test.h',
      'myapp/cefclient/browser/default_client_handler.cc',
      'myapp/cefclient/browser/default_client_handler.h',
      'myapp/cefclient/browser/dialog_test.cc',
      'myapp/cefclient/browser/dialog_test.h',
      'myapp/cefclient/browser/hang_test.cc',
      'myapp/cefclient/browser/hang_test.h',
      'myapp/cefclient/browser/cef_query_handler.cc',
      'myapp/cefclient/browser/cef_query_handler.h',
      'myapp/cefclient/browser/custom_scheme.cc',
      'myapp/cefclient/browser/custom_scheme.h',
      'myapp/cefclient/browser/image_cache.cc',
      'myapp/cefclient/browser/image_cache.h',
      'myapp/cefclient/browser/main_context.cc',
      'myapp/cefclient/browser/main_context.h',
      'myapp/cefclient/browser/main_context_impl.cc',
      'myapp/cefclient/browser/main_context_impl.h',
      'myapp/cefclient/browser/media_router_test.cc',
      'myapp/cefclient/browser/media_router_test.h',
      'myapp/cefclient/browser/my_response_filter.cc',
      'myapp/cefclient/browser/my_response_filter.h',
      'myapp/cefclient/browser/osr_dragdrop_events.h',
      'myapp/cefclient/browser/osr_renderer.h',
      'myapp/cefclient/browser/osr_renderer.cc',
      'myapp/cefclient/browser/osr_renderer_settings.h',
      'myapp/cefclient/browser/preferences_test.cc',
      'myapp/cefclient/browser/preferences_test.h',
      'myapp/cefclient/browser/resource.h',
      'myapp/cefclient/browser/response_filter_test.cc',
      'myapp/cefclient/browser/response_filter_test.h',
      'myapp/cefclient/browser/root_window.cc',
      'myapp/cefclient/browser/root_window.h',
      'myapp/cefclient/browser/root_window_create.cc',
      'myapp/cefclient/browser/root_window_manager.cc',
      'myapp/cefclient/browser/root_window_manager.h',
      'myapp/cefclient/browser/root_window_views.cc',
      'myapp/cefclient/browser/root_window_views.h',
      'myapp/cefclient/browser/scheme_test.cc',
      'myapp/cefclient/browser/scheme_test.h',
      'myapp/cefclient/browser/server_test.cc',
      'myapp/cefclient/browser/server_test.h',
      'myapp/cefclient/browser/task_manager_test.cc',
      'myapp/cefclient/browser/task_manager_test.h',
      'myapp/cefclient/browser/temp_window.h',
      'myapp/cefclient/browser/test_runner.cc',
      'myapp/cefclient/browser/test_runner.h',
      'myapp/cefclient/browser/urlrequest_test.cc',
      'myapp/cefclient/browser/urlrequest_test.h',
      'myapp/cefclient/browser/views_menu_bar.cc',
      'myapp/cefclient/browser/views_menu_bar.h',
      'myapp/cefclient/browser/views_overlay_browser.cc',
      'myapp/cefclient/browser/views_overlay_browser.h',
      'myapp/cefclient/browser/views_overlay_controls.cc',
      'myapp/cefclient/browser/views_overlay_controls.h',
      'myapp/cefclient/browser/views_style.cc',
      'myapp/cefclient/browser/views_style.h',
      'myapp/cefclient/browser/views_window.cc',
      'myapp/cefclient/browser/views_window.h',
      'myapp/cefclient/browser/window_test.cc',
      'myapp/cefclient/browser/window_test.h',
      'myapp/cefclient/browser/window_test_runner.cc',
      'myapp/cefclient/browser/window_test_runner.h',
      'myapp/cefclient/browser/window_test_runner_views.cc',
      'myapp/cefclient/browser/window_test_runner_views.h',
    ],
    'myapp_cefclient_sources_common': [
      'myapp/cefclient/common/client_app_delegates_common.cc',
      'myapp/cefclient/common/custom_scheme_common.cc',
      'myapp/cefclient/common/custom_scheme_common.h',
      'myapp/cefclient/common/scheme_test_common.cc',
      'myapp/cefclient/common/scheme_test_common.h',
      'myapp/cefclient/hostclr/HostCLR.cpp',
      'myapp/cefclient/hostclr/HostCLR.h',
      'myapp/cefclient/hostclr/JavaScriptCaller.h',
      'myapp/cefclient/hostclr/auth_credentials.cc',
      'myapp/cefclient/hostclr/auth_credentials.h',
      'myapp/cefclient/hostclr/credui_prompt.cc',
      'myapp/cefclient/hostclr/credui_prompt.h',
      'myapp/cefclient/hostclr/js_arg.h',
      'myapp/cefclient/hostclr/js_arg_v8.h',
      'myapp/cefclient/hostclr/js_dialog_handler.cc',
      'myapp/cefclient/hostclr/js_dialog_handler.h',
      'myapp/cefclient/hostclr/native_callbacks.cc',
      'myapp/cefclient/hostclr/native_callbacks.h',
      'myapp/cefclient/hostclr/path_utils.cpp',
      'myapp/cefclient/hostclr/path_utils.h',
    ],
    'myapp_cefclient_sources_renderer': [
      'myapp/cefclient/renderer/client_app_delegates_renderer.cc',
      'myapp/cefclient/renderer/client_renderer.cc',
      'myapp/cefclient/renderer/client_renderer.h',
      'myapp/cefclient/renderer/ipc_performance_test.cc',
      'myapp/cefclient/renderer/ipc_performance_test.h',
      'myapp/cefclient/renderer/performance_test.cc',
      'myapp/cefclient/renderer/performance_test.h',
      'myapp/cefclient/renderer/performance_test_setup.h',
      'myapp/cefclient/renderer/performance_test_tests.cc',
    ],
    'myapp_cefclient_sources_resources': [
      'myapp/cefclient/resources/binary_transfer.html',
      'myapp/cefclient/resources/binding.html',
      'myapp/cefclient/resources/components.html',
      'myapp/cefclient/resources/config.html',
      'myapp/cefclient/resources/dialogs.html',
      'myapp/cefclient/resources/draggable.html',
      'myapp/cefclient/resources/hang.html',
      'myapp/cefclient/resources/ipc_performance.html',
      'myapp/cefclient/resources/localstorage.html',
      'myapp/cefclient/resources/logo.png',
      'myapp/cefclient/resources/media_router.html',
      'myapp/cefclient/resources/menu_icon.1x.png',
      'myapp/cefclient/resources/menu_icon.2x.png',
      'myapp/cefclient/resources/other_tests.html',
      'myapp/cefclient/resources/performance.html',
      'myapp/cefclient/resources/performance2.html',
      'myapp/cefclient/resources/pip.html',
      'myapp/cefclient/resources/preferences.html',
      'myapp/cefclient/resources/response_filter.html',
      'myapp/cefclient/resources/server.html',
      'myapp/cefclient/resources/task_manager.html',
      'myapp/cefclient/resources/transparency.html',
      'myapp/cefclient/resources/urlrequest.html',
      'myapp/cefclient/resources/websocket.html',
      'myapp/cefclient/resources/window.html',
      'myapp/cefclient/resources/xmlhttprequest.html',
    ],
    'myapp_cefclient_sources_win': [
      'myapp/cefclient/browser/browser_window_osr_win.cc',
      'myapp/cefclient/browser/browser_window_osr_win.h',
      'myapp/cefclient/browser/browser_window_std_win.cc',
      'myapp/cefclient/browser/browser_window_std_win.h',
      'myapp/cefclient/browser/main_context_impl_win.cc',
      'myapp/cefclient/browser/main_message_loop_multithreaded_win.cc',
      'myapp/cefclient/browser/main_message_loop_multithreaded_win.h',
      'myapp/cefclient/browser/osr_accessibility_helper.cc',
      'myapp/cefclient/browser/osr_accessibility_helper.h',
      'myapp/cefclient/browser/osr_accessibility_node.cc',
      'myapp/cefclient/browser/osr_accessibility_node.h',
      'myapp/cefclient/browser/osr_accessibility_node_win.cc',
      'myapp/cefclient/browser/osr_dragdrop_win.cc',
      'myapp/cefclient/browser/osr_dragdrop_win.h',
      'myapp/cefclient/browser/osr_ime_handler_win.cc',
      'myapp/cefclient/browser/osr_ime_handler_win.h',
      'myapp/cefclient/browser/osr_d3d11_win.cc',
      'myapp/cefclient/browser/osr_d3d11_win.h',
      'myapp/cefclient/browser/osr_render_handler_win.cc',
      'myapp/cefclient/browser/osr_render_handler_win.h',
      'myapp/cefclient/browser/osr_render_handler_win_d3d11.cc',
      'myapp/cefclient/browser/osr_render_handler_win_d3d11.h',
      'myapp/cefclient/browser/osr_render_handler_win_gl.cc',
      'myapp/cefclient/browser/osr_render_handler_win_gl.h',
      'myapp/cefclient/browser/osr_window_win.cc',
      'myapp/cefclient/browser/osr_window_win.h',
      'myapp/cefclient/browser/resource_util_win_idmap.cc',
      'myapp/cefclient/browser/root_window_win.cc',
      'myapp/cefclient/browser/root_window_win.h',
      'myapp/cefclient/browser/temp_window_win.cc',
      'myapp/cefclient/browser/temp_window_win.h',
      'myapp/cefclient/browser/window_test_runner_win.cc',
      'myapp/cefclient/browser/window_test_runner_win.h',
      'myapp/cefclient/cefclient_win.cc',
    ],
    'myapp_cefclient_sources_resources_win': [
      'myapp/cefclient/win/cefclient.exe.manifest',
      'myapp/cefclient/win/webagent.ico',
      'myapp/cefclient/win/small.ico',
    ],
    'myapp_cefclient_sources_resources_win_rc': [
      'myapp/cefclient/win/cefclient.rc',
    ],
    'myapp_cefclient_sources_linux': [
      'myapp/cefclient/browser/browser_window_osr_gtk.cc',
      'myapp/cefclient/browser/browser_window_osr_gtk.h',
      'myapp/cefclient/browser/browser_window_std_gtk.cc',
      'myapp/cefclient/browser/browser_window_std_gtk.h',
      'myapp/cefclient/browser/dialog_handler_gtk.cc',
      'myapp/cefclient/browser/dialog_handler_gtk.h',
      'myapp/cefclient/browser/main_context_impl_posix.cc',
      'myapp/cefclient/browser/main_message_loop_multithreaded_gtk.cc',
      'myapp/cefclient/browser/main_message_loop_multithreaded_gtk.h',
      'myapp/cefclient/browser/print_handler_gtk.cc',
      'myapp/cefclient/browser/print_handler_gtk.h',
      'myapp/cefclient/browser/resource_util_linux.cc',
      'myapp/cefclient/browser/root_window_gtk.cc',
      'myapp/cefclient/browser/root_window_gtk.h',
      'myapp/cefclient/browser/temp_window_x11.cc',
      'myapp/cefclient/browser/temp_window_x11.h',
      'myapp/cefclient/browser/util_gtk.cc',
      'myapp/cefclient/browser/util_gtk.h',
      'myapp/cefclient/browser/window_test_runner_gtk.cc',
      'myapp/cefclient/browser/window_test_runner_gtk.h',
      'myapp/cefclient/cefclient_gtk.cc',
    ],
    'myapp_cefsimple_sources_common': [
      'myapp/cefsimple/simple_app.cc',
      'myapp/cefsimple/simple_app.h',
      'myapp/cefsimple/simple_handler.cc',
      'myapp/cefsimple/simple_handler.h',
      'myapp/cefclient/hostclr/path_utils.cpp',
      'myapp/cefclient/hostclr/path_utils.h',
    ],
    'myapp_cefsimple_sources_win': [
      'myapp/cefsimple/cefsimple_win.cc',
      'myapp/cefsimple/resource.h',
      'myapp/cefsimple/simple_handler_win.cc',
    ],
    'myapp_cefsimple_sources_resources_win': [
      'myapp/cefsimple/win/cefsimple.exe.manifest',
      'myapp/cefsimple/win/websimple.ico',
      'myapp/cefsimple/win/small.ico',
    ],
    'myapp_cefsimple_sources_resources_win_rc': [
      'myapp/cefsimple/win/cefsimple.rc',
    ],
    'myapp_cefsimple_sources_linux': [
      'myapp/cefsimple/cefsimple_linux.cc',
      'myapp/cefsimple/simple_handler_linux.cc',
    ],
    'myapp_shared_sources_mac': [
      'myapp/shared/browser/main_message_loop_external_pump_mac.mm',
      'myapp/shared/browser/resource_util_mac.mm',
      'myapp/shared/browser/resource_util_posix.cc',
    ],
    'myapp_shared_sources_mac_helper': [
      'myapp/shared/process_helper_mac.cc',
    ],
    'myapp_cefclient_sources_mac': [
      'myapp/cefclient/browser/browser_window_osr_mac.h',
      'myapp/cefclient/browser/browser_window_osr_mac.mm',
      'myapp/cefclient/browser/browser_window_std_mac.h',
      'myapp/cefclient/browser/browser_window_std_mac.mm',
      'myapp/cefclient/browser/main_context_impl_posix.cc',
      'myapp/cefclient/browser/osr_accessibility_helper.cc',
      'myapp/cefclient/browser/osr_accessibility_helper.h',
      'myapp/cefclient/browser/osr_accessibility_node.cc',
      'myapp/cefclient/browser/osr_accessibility_node.h',
      'myapp/cefclient/browser/osr_accessibility_node_mac.mm',
      'myapp/cefclient/browser/root_window_mac.h',
      'myapp/cefclient/browser/root_window_mac.mm',
      'myapp/cefclient/browser/temp_window_mac.h',
      'myapp/cefclient/browser/temp_window_mac.mm',
      'myapp/cefclient/browser/text_input_client_osr_mac.h',
      'myapp/cefclient/browser/text_input_client_osr_mac.mm',
      'myapp/cefclient/browser/util_mac.h',
      'myapp/cefclient/browser/util_mac.mm',
      'myapp/cefclient/browser/views_window_mac.mm',
      'myapp/cefclient/browser/window_test_runner_mac.h',
      'myapp/cefclient/browser/window_test_runner_mac.mm',
      'myapp/cefclient/cefclient_mac.mm',
      'myapp/cefclient/hostclr/credui_prompt_mac.mm',
    ],
    'myapp_cefsimple_sources_mac': [
      'myapp/cefsimple/cefsimple_mac.mm',
      'myapp/cefsimple/simple_handler_mac.mm',
    ],
    'myapp_cefsimple_sources_mac_helper': [
      'myapp/cefsimple/process_helper_mac.cc',
    ],
  },
}
